// -*- C++ -*-
//
// $Id: SOCK_Acceptor.inl 69051 2005-10-28 16:14:56Z ossama $

ACE_BEGIN_VERSIONED_NAMESPACE_DECL

ACE_INLINE
ACE_SOCK_Acceptor::~ACE_SOCK_Acceptor (void)
{
  ACE_TRACE ("ACE_SOCK_Acceptor::~ACE_SOCK_Acceptor");
}

ACE_END_VERSIONED_NAMESPACE_DECL
