
// -*- C++ -*-
// $Id: Version.h 79662 2007-09-19 09:10:32Z johnnyw $
// This is file was automatically generated by \$ACE_ROOT/bin/make_release.

#define ACE_MAJOR_VERSION 5
#define ACE_MINOR_VERSION 6
#define ACE_BETA_VERSION 1
#define ACE_VERSION "5.6.1"
