/* $Id: kokyu_config.h 55697 2004-01-28 01:35:45Z storri $ */
#ifndef KOKYU_CONFIG_H
#define KOKYU_CONFIG_H

#define CONFIG_DSTREAM_DSRT_DISPATCH
#define CONFIG_DSTREAM_DSRT_CV_DISPATCH
#define CONFIG_DSTREAM_DSRT_DIRECT_DISPATCH
#define CONFIG_DSTREAM_DSRT_DISPATCH_IMPL

#endif /* KOKYU_CONFIG_H */
